build: false
environment:
  PYTHONWARNINGS: all
  DJANGO_SETTINGS_MODULE: config.settings.test
  global:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: Password12!
    POSTGRES_DB: sarisari_db
  matrix:
    - PYTHON: "C:/Python36"
      DJANGO_VERSION: "Django==2.0,<2.1"
matrix:
  fast_finish: true
install:
  - "%PYTHON%/python.exe -m pip install -r \"requirements/test.txt\""
  - "C:/Program Files/PostgreSQL/10.3/bin/createdb %POSTGRES_DB%"
  - "%PYTHON%/python.exe manage.py migrate"
test_script:
  - "%PYTHON%/python.exe manage.py test"
  - "%PYTHON%/python.exe py.test"
services:
  - postgresql103
