build: false
environment:
  PYTHONWARNINGS: all
  DJANGO_SETTINGS_MODULE: config.settings.test
  global:
    - PGUSER: postgres
      PGPASSWORD: Password12!
      PGDB: sarisari_db
      PATH: C:\Program Files\PostgreSQL\10.3\bin\;%PATH%
  matrix:
    - PYTHON: "C:/Python36"
      DJANGO_VERSION: "Django==2.0,<2.1"
matrix:
  fast_finish: true
install:
  - "%PYTHON%/python.exe -m pip install -r \"requirements/test.txt\""
  - createdb %PGDB%
  - "%PYTHON%/python.exe -m manage.py migrate"
test_script:
  - "%PYTHON%/python.exe -m manage.py test"
  - "%PYTHON%/python.exe -m py.test"
services:
  - postgresql103
