services:
  - postgresql101

environment:
  PYTHONIOENCODING: "utf-8"
  PYTHONWARNINGS: all
  DJANGO_SETTINGS_MODULE: config.settings.test
  REQUIREMENTS_FILE: "requirements/appveyor.txt"
  global:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: Password12!
    DB_HOST: localhost
    DB_PORT: 5432
    POSTGRES_DB: sarisari_db
    DATABASE_URL: "postgres://%POSTGRES_USER%:%POSTGRES_PASSWORD%@%DB_HOST%:%DB_PORT%/%POSTGRES_DB%"
  matrix:
    - PYTHON: "C:/Python36"
      DJANGO_VERSION: "Django==2.0,<2.1"

matrix:
  fast_finish: true

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:\\Python*"
  - "ECHO %PATH%"
  - ps: "ls %PROGRAMFILES%\\PostgreSQL\\*"

build: off

build_script:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET PATH=%PROGRAMFILES%\PostgreSQL\10.1\bin\;%PATH%

install:
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%\\python.exe C:\\get-pip.py"
  - "%PYTHON%\\Scripts\\pip.exe install -r %REQUIREMENTS_FILE%"
  - "%PYTHON%\\python.exe manage.py migrate"

before_test:
  - psql -U %PGUSER% -c "CREATE USER %POSTGRES_USER% WITH PASSWORD '%POSTGRES_PASSWORD%';"
  - psql -U %PGUSER% -c "ALTER USER %POSTGRES_USER% CREATEDB;"
  - psql -U %PGUSER% -c "ALTER ROLE %POSTGRES_USER% SET client_encoding TO 'utf8';"
  - psql -U %PGUSER% -c "ALTER ROLE %POSTGRES_USER% SET default_transaction_isolation TO 'read committed';"
  - psql -U %PGUSER% -c "ALTER ROLE %POSTGRES_USER% SET timezone TO 'UTC';"
  - psql -U %PGUSER% -c "CREATE DATABASE %POSTGRES_DB%;"
  - psql -U %PGUSER% -c "GRANT ALL PRIVILEGES ON DATABASE %POSTGRES_DB% TO %POSTGRES_USER%;"

test_script:
  - "%PYTHON%\\Scripts\\pip.exe --version"
  
  # Make sure we are not in a directory where we might import a
  # different version of psycopg2
  - CD \
  
  # Print psycopg and libpq versions
  - "%PYTHON%\\python.exe -c \"import psycopg2; print(psycopg2.__version__)\""
  - "%PYTHON%\\python.exe -c \"import psycopg2; print(psycopg2.__libpq_version__)\""
  - "%PYTHON%\\python.exe -c \"import psycopg2; print(psycopg2.extensions.libpq_version())\""
  
  # Test
  - "%PYTHON%\\python.exe manage.py test"
  - "%PYTHON%\\python.exe -m coverage run manage.py test"
  - "%PYTHON%\\python.exe -m py.test"
