platform:
  - x64

services:
  - postgresql103

environment:
  PYTHONIOENCODING: "utf-8"
  PYTHONWARNINGS: all
  DJANGO_SETTINGS_MODULE: config.settings.test
  REQUIREMENTS_FILE: "requirements/appveyor.txt"
  global:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: Password12!
    DB_HOST: localhost
    DB_PORT: 5432
    POSTGRES_DB: sarisari_db
    DATABASE_URL: "postgres://%POSTGRES_USER%:%POSTGRES_PASSWORD%@%DB_HOST%:%DB_PORT%/%POSTGRES_DB%"
  matrix:
    - PYTHON: "C:/Python36"
      DJANGO_VERSION: "Django==2.0,<2.1"

matrix:
  fast_finish: true

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

before_build:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET PATH=C:\Program Files\PostgreSQL\10.3\bin\;%PATH%
  - psql -U %PGUSER% -c "CREATE USER %POSTGRES_USER% WITH PASSWORD '%POSTGRES_PASSWORD%';"
  - psql -U %PGUSER% -c "ALTER USER %POSTGRES_USER% CREATEDB;"
  - psql -U %PGUSER% -c "ALTER ROLE %POSTGRES_USER% SET client_encoding TO 'utf8';"
  - psql -U %PGUSER% -c "ALTER ROLE %POSTGRES_USER% SET default_transaction_isolation TO 'read committed';"
  - psql -U %PGUSER% -c "ALTER ROLE %POSTGRES_USER% SET timezone TO 'UTC';"
  - psql -U %PGUSER% -c "CREATE DATABASE %POSTGRES_DB%;"
  - psql -U %PGUSER% -c "GRANT ALL PRIVILEGES ON DATABASE %POSTGRES_DB% TO %POSTGRES_USER%;"

install:
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install -r %REQUIREMENTS_FILE%"
  - "%PYTHON%/python.exe manage.py migrate"

test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/python.exe manage.py test"
  - "%PYTHON%/python.exe -m coverage run manage.py test"
  - "%PYTHON%/python.exe -m py.test"
