sudo: true
language: python
python:
  - "3.6"
env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.test
    - POSTGRES_USER=sarisari_dev
    - POSTGRES_PASSWORD=sarisari_password
    - DB_HOST=localhost
    - DB_PORT=5432
    - POSTGRES_DB=sarisari_db
    - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$DB_HOST:$DB_PORT/$POSTGRES_DB
install:
  - ./utility/install_os_dependencies.sh
  - ./utility/install_python_dependencies.sh test
  - ./utility/initialize_database.sh
script:
  - python manage.py migrate
  - python manage.py test
  - py.test
