# Generated by Django 2.0.4 on 2018-04-13 17:37

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('datetime_created', models.DateTimeField(editable=False, verbose_name='Created')),
                ('datetime_updated', models.DateTimeField(editable=False, verbose_name='Modified')),
                ('address', models.TextField(verbose_name='Address')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('datetime_created', models.DateTimeField(editable=False, verbose_name='Created')),
                ('datetime_updated', models.DateTimeField(editable=False, verbose_name='Modified')),
                ('number_type', models.CharField(choices=[('MOB', 'Mobile'), ('FAX', 'Fax'), ('WRK', 'Work'), ('LND', 'Landline')], default='MOB', max_length=3, verbose_name='Type')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Number')),
            ],
            options={
                'verbose_name': 'phone number',
                'verbose_name_plural': 'phone number',
            },
        ),
    ]
